version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Check clang-format version
          command: |
            echo "lsb_release"
            set +e
            lsb_release -a
            echo "hostnamectl"
            set +e
            hostnamectl

      - run:
          name: Install build tools
          command: 'apt-get update && apt-get install -y gcc g++ && gcc --version'

      - run:
          name: Build with g++
          command: 'g++ hwcpp/hellowolrd.cc -o helloworld'