version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Check clang-format version
          command: |
            apt-get update
            set +e
            apt-get install -y clang-format
            set +e
            clang-format --version
            set +e
            clang-format-3.8 --version

      - run:
          name: Check clang version
          command: |
            apt-get update
            apt-get install -y clang
            set +e
            clang --version

      - run:
          name: Install build tools
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Build with g++
          command: 'g++ hwcpp/hellowolrd.cc -o helloworld'