version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Check system version
          command: 'uname -a'

      - run:
          name: Check cmake version
          command: 'apt-get update && apt-get install -y cmake && cmake --version'

      - run:
          name: Check clang version
          command: 'apt-get update && apt-get install -y clang && clang-format --version'

      - run:
          name: Install build tools
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Build with g++
          command: 'g++ hwcpp/hellowolrd.cc -o helloworld'