version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install build tools
          command: 'apt-get update && apt-get install -y gcc g++ cmake'

      - run:
          name: Build with CMake
          command: |
            cd hwcpp
            mkdir build
            cd build
            cmake ..
            make

      - run:
          name: Run the application
          command: ./hwcpp/build/helloworld
